### ISSUE TITLE
Replacement of league/flysystem-dropbox

### ISSUE THREAD

**Issue by neoacevedo** [2amigos/yii2-flysystem-component#2]
Hi, I received a notice about league/flysystem-dropbox

> league/flysystem-dropbox is abandoned, you should avoid using it. Use spatie/flysystem-dropbox instead.

I think this package should be addressed to the new dropbox dependency.

Regards.

**Comment by tonydspaniard** [comment]
Thanks @neoacevedo

**Comment by tonydspaniard** [comment]
done by @Slayvin
