### ISSUE TITLE
Get Url from storage

### ISSUE THREAD

**Issue by neoacevedo** [2amigos/yii2-flysystem-component#3]
There is a mode to get the file URL?

**Comment by tonydspaniard** [comment]
For which adapter?

**Comment by neoacevedo** [comment]
azure, s3, gcs

**Comment by tonydspaniard** [comment]
You could access that via the adapter. For example, lets assume we have `fs` component configured with AWS:   `Yii::$app->fs->getAdapter()->getClient()->getObjectUrl($bucket, $key);`
